# Generated by Django 4.0.6 on 2022-07-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasktolabel_task_labels_tasktolabel_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee',
            new_name='executor',
        ),
    ]
